### ISSUE TITLE
Telegram alerts are not working

### ISSUE THREAD

**Issue by vvavepacket** [GuillaumeMiralles/prysm-grafana-dashboard#14]
I setup my grafana dashboard and was able to verify that it is connecting to telegram bot by hitting the test button. I am able to get the test message.

However, when I try to disable my validator node by shutting it down, I do not get any alerts from telegram bot. I tried waiting for more than 1 minute and still didn't get alerted by Telegram Bot. 

I'm attaching a screenshot of my dashboard, the alerts window seems empty.

Is there any steps or configuration that is missing?

![image](https://user-images.githubusercontent.com/8295642/99922739-0f027000-2d00-11eb-98e0-489b6e57d9ef.png)

**Comment by GuillaumeMiralles** [comment]
Talked about this issue directly on discord. The alert chanel wasn't set as default, then alerts couldn't be send in any alert chanel.
![image](https://user-images.githubusercontent.com/23481418/100232799-21abbd80-2f29-11eb-9f07-b5c5541c8046.png)


In order to fix it, it was required either to set the alert as default, or to set the alert chanel in each alert rules
