### ISSUE TITLE
unable to import dashboard using API

### ISSUE THREAD

**Issue by koala345** [GuillaumeMiralles/prysm-grafana-dashboard#3]
hi there, I'm working on some (Ansible) scripts to automate the provisioning of a eth2 validator with prometheus, Grafana and your dashboard. I'm roughly automating these instructions: 
https://medium.com/@SomerEsat/guide-to-staking-on-ethereum-2-0-ubuntu-prysm-witti-2b972e697918
but for the Grafana setup I'm using the API (POST /api/dashboards/db), rather then manually copying and pasting the content into the webpage. 

However when I try to import the 'less_10_validators.json' content I receive the following API error message back: 

```
{'message': 'Alert validation error: Data source used by alert rule not found, alertName=WARN NODE/VALIDATOR: The process just restarted, datasource='}
```
it will not import the dashboard. Any idea what that means? When I use the Grafana UI to import the json, it will accept it, although I also get an error popup with the message: 

```
Templating
Template variables could not be initialized: Unable to load datasource meta data
```
I'm using Grafana version 7.0.3
thanks

**Comment by GuillaumeMiralles** [comment]
Could you please try to import the dashboard "less_10_validators.json" again through API. I might have fixed the issue. But that's weird that the import through API or copy paste aren't the same.

From what I understand here, API doesn't support alert rules if the datasource is set to Default, while with copy paste this isn't a problem at all. I changed all the datasource to Prometheus, which might fixed this.

What is exactly the second issue? Do you still have access to the dashboard? Or it's a blocking error?
It might be because you don't have the cryptowat third party tool running yet with prometheus getting the data from it.
You can see how to run this third party tool here: https://github.com/GuillaumeMiralles/prysm-grafana-dashboard/blob/master/currency_converter.md

Let me know how it goes

**Comment by koala345** [comment]
thanks for helping to investigate this. It does seem like Grafana treats data received by the API a bit different than data received by its web forms. 
I tried again with the new content, but now when I post the content to /api/dashboards/db I get the error reponse 
```
{'message': 'Dashboard not found', 'status': 'not-found'}
```
I think it narrowed it down to the 'id' property in your content. The API spec states that to create a new dashboard, that id should have value null. When I tried setting it to null, I got an OK response and the dashboard now appears to be successfully created: 
```
{'id': 4, 'slug': 'eth-staking-dashboard', 'status': 'success', 'uid': 't2yHaa3Zz', 'url': '/d/t2yHaa3Zz/eth-staking-dashboard', 'version': 1}
```
Any chance you could null out that value in your version? 

In regards to your other question: when the dashboard is added through the UI I do see that error popup, but the dashboard does appear to be added succesfully. I don't have my validator fully up and running yet so can't say for sure until I have prometheus actually publishing data.

**Comment by GuillaumeMiralles** [comment]
There are a lot of "id" in the json, but those are for the panels inside of the dashboard. There is no "id" for the dashboard directly, or are you talking about the field `uid` ?


For the second issue, then I haven't seen that myself when I tried without the third party tool cryptowat, but I believe that it's just a warning for the template variable that receive no data from cryptowat. I think it's ok to ignore it

**Comment by koala345** [comment]
The 'id' on line 21 of less_10_validators.json appears to be at the root of the json object... that's the one I changed to null. 

I do  see the template error immediately after importing the dashboard, but after a little while (something in the order of seconds) I don't see it anymore upon refreshing the page. Perhaps it's only happening before the first time the Prometheus datasource fetches data.

**Comment by GuillaumeMiralles** [comment]
Ok I thought this id was for the readme panel, never mind.

So you can try again to import it now, I changed it to null, I tried to import it manually and it works, but I will have to be careful with it because the id is setting back to 1 when I save it, so if I don't change it back when I update the dashboard here, I might break your import again.
Sorry in advance it might happens 😅 



About the second issue, it's all good, I tried it and got the pop up too
![image](https://user-images.githubusercontent.com/23481418/84364669-af405e80-abd0-11ea-842e-4711309c4527.png)


This won't affect the dashboard, this just warn the user that the template variable can't fetch any data from the metric (since it doesn't exist because the cryptowat tool isn't running)

**Comment by koala345** [comment]
if it requires a manual tweak then it's probably not a robust process to have to remember every time you update it. Let me see what I can do to alter this property programmatically before sending it to the api. It should probably only take a couple of lines of Python code. Thanks for your help anyway.

**Comment by GuillaumeMiralles** [comment]
Yes you could parse the JSON, find the first occurence of `id` then replace the value of it.
That's not much work, and it will prevent to have future bug on your side. Let me know please if you did implemented this in your script, so I won't have to think to change the id each time

**Comment by koala345** [comment]
I'm using the Ansible command grafana_dashboard now to import your dashboard. This worked fine but I just realized since I'm grabbing it directly from your project and in there the id is currently set to null. On your next update, just leave the ID to the original value and I will try again and fix on my side if necessary.

**Comment by GuillaumeMiralles** [comment]
Ok, I'm setting the id back to the original values now
